export const monthMap = {
    'janvier': '01',
    'january': '01',
    'février': '02',
    'february': '02',
    'mars': '03',
    'march': '03',
    'avril': '04',
    'april': '04',
    'mai': '05',
    'may': '05',
    'juin': '06',
    'june': '06',
    'juillet': '07',
    'july': '07',
    'août': '08',
    'august': '08',
    'septembre': '09',
    'september': '09',
    'octobre': '10',
    'october': '10',
    'novembre': '11',
    'november': '11',
    'décembre': '12',
    'december': '12'
}